spring:
  datasource:
    url: jdbc:mysql://172-31-0-189:3306/moaguide?serverTimezone=Asia/Seoul
    username: moaguide
    password: whrkrxnwkahdkrkdlem
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      minimum-idle: 5
      maximum-pool-size: 10
      idle-timeout: 300000
      max-lifetime: 1800000
      connection-timeout: 20000
      validation-timeout: 5000
      leak-detection-threshold: 2000
      keepalive-time: 0
      connection-test-query: SELECT 1
  data:
    redis:
      host: 172.31.5.227
      port: 6379
      repositories:
        enabled: false

