spring:
  datasource:
    url: jdbc:mysql://moaguide.ctwmmmi82b0n.ap-northeast-2.rds.amazonaws.com:3306/moaguide?serverTimezone=UTC
    username: moaguide
    password: ahdkrkdlem1!
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      minimum-idle: 5
      maximum-pool-size: 10
      idle-timeout: 300000
      max-lifetime: 1800000
      connection-timeout: 20000
      validation-timeout: 5000
      leak-detection-threshold: 2000
      keepalive-time: 0
      connection-test-query: SELECT 1
  data:
    redis:
      host: 172.31.5.227
      port: 6379
      repositories:
        enabled: false
      coolsms:
        apiKey: ${COOLSMS_API_KEY:NCS6DIOVFX0WIBEE}
        apiSecret: ${COOLSMS_API_SECRET:4DWOYEGVJ3MPVSE8ZRWQYCG4ZSD9Y1MY}
        senderNumber: ${COOLSMS_SENDER_NUMBER:01022476408}
#  elasticsearch:
#    uris: http://172.31.5.227:9201
#    username: elastic                   # elastic 사용자 이름
#    password: moaguide1!                # elastic 사용자의 비밀번호
#    connection-timeout: 5000
#    socket-timeout: 10000
#  ssl:
#    certificate-authorities: classpath:certs/ca/ca.crt
#    truststore-password: moaguide1!
