spring:
  datasource:
    url: jdbc:mysql://moa.ctwmmmi82b0n.ap-northeast-2.rds.amazonaws.com:3306/moaguide?serverTimezone=UTC
    username: moaguide
    password: whrkrxnwkahdkrkdlem
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      minimum-idle: 5
      maximum-pool-size: 10
      idle-timeout: 300000
      max-lifetime: 1800000
      connection-timeout: 20000
      validation-timeout: 5000
      leak-detection-threshold: 2000
      keepalive-time: 0
      connection-test-query: SELECT 1
  data:
    redis:
      host: 172.31.5.227
      port: 6379
      repositories:
        enabled: false
  elasticsearch:
    uris: https://172.23.0.3:9200
    username: elastic
    password: moaguide1!
    connection-timeout: 50000
    socket-timeout: 100000
    ssl:
      enabled: true
      trust-store-location: /app/resources/certs/ca/ca.crt
      trust-store-type: PEM
